# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend.yaml
  - bff-service.yaml
  - user-service.yaml
  - workspace-channel-service.yaml
  - message-service.yaml
  - notification-service.yaml
